# Configuration values for mini-games

# The chosen language for Launchpad. You can use "en" or any custom language specified in strings.yml
language: en
parkour:
  # Whether to enforce the order in which a player must reach checkpoints. Enabling this ensures that a player cannot
  # trigger a previous checkpoint by accident. It also ensures players cannot skip a checkpoint, even if the arena
  # layout makes it possible.
  enforceCheckpointOrder: false
  
  # Whether grouped dropper arenas must be played in the correct sequence
  mustDoGroupedInSequence: true
  
  # Whether records won't be registered unless the player has already beaten all arenas in a group. That means players
  # are required to do a second play-through to register a record for a grouped arena.
  ignoreRecordsUntilGroupBeatenOnce: false
  
  # The blocks compromising parkour arenas' kill planes. Add any materials you want to use for the "bottom" of your
  # parkour arenas.
  killPlaneBlocks:
    - LAVA
    - MAGMA_BLOCK
  
  # The blocks treated as obstacles in a parkour arena, which will trigger a loss in any direction
  obstacleBlocks:
    - END_ROD
    - LIGHTNING_ROD
    - CHAIN
dropper:
  # Whether to block using the shift key to drop faster than the intended drop speed
  blockSneaking: true
  
  # Whether to block using the sprint key for slightly improved air speed
  blockSprinting: true
  
  # The vertical velocity used as default for all arenas. Must be greater than 0. 3.92 is the max speed of a falling
  # player.
  verticalVelocity: 1.0
  
  # The horizontal velocity used as default for all arenas (technically fly-speed). Must be between 0 (exclusive) and 1 
  # (inclusive).
  horizontalVelocity: 1.0
  
  # The number of seconds before the randomly inverted game-mode switches between normal and inverted movement (0, 3600]
  randomlyInvertedTimer: 7
  
  # Whether grouped dropper arenas must be played in the correct sequence
  mustDoGroupedInSequence: true
  
  # Whether records won't be registered unless the player has already beaten all arenas in a group. That means players
  # are required to do a second play-through to register a record for a grouped arena.
  ignoreRecordsUntilGroupBeatenOnce: false
  
  # Whether a player must do the normal/default game-mode before playing any other game-modes
  mustDoNormalModeFirst: true
  
  # A whitelist for which blocks won't trigger a loss when hit/passed through. The win block check happens before the
  # loss check, so even blocks on the whitelist can be used as the win-block. "+" denotes a material tag.
  blockWhitelist:
    - WATER
    - LAVA
    - +WALL_SIGNS
    - +STANDING_SIGNS
    - STRUCTURE_VOID
    - WALL_TORCH
    - SOUL_WALL_TORCH
    - REDSTONE_WALL_TORCH
    - +BANNERS
    - +BUTTONS
    - +CORALS
    - +WALL_CORALS
    - LIGHT
shared:
  # This decides how far inside a non-solid block the player must go before detection triggers (-1, 0). The closer to -1
  # it is, the more accurate it will seem to the player, but the likelihood of not detecting the hit increases.
  liquidHitBoxDepth: -0.8

  # This decides the distance the player must be from a block below them before a hit triggers (0, 1). If too low, the 
  # likelihood of detecting the hit decreases, but it won't look like the player hit the block without being near.
  solidHitBoxDistance: 0.2