name: Dropper
version: '${project.version}'
main: net.knarcraft.dropper.Dropper
api-version: 1.19
description: A plugin for dropper mini-games

commands:
  dropperreload:
    aliases:
      - dreload
    permission: dropper.admin
    usage: /<command>
    description: Reloads all data from disk
  dropperlist:
    aliases:
      - dlist
    permission: dropper.join
    usage: /<command>
    description: Used to list all current dropper arenas
  dropperjoin:
    aliases:
      - djoin
    permission: dropper.join
    usage: |
      /<command> <arena> [mode]
      Mode can be used to select challenge modes which can be played after beating the arena.
      deaths = A least-deaths competitive game-mode
      time = A shortest-time competitive game-mode
    description: Used to join a dropper arena
  dropperleave:
    aliases:
      - dleave
    permission: dropper.join
    usage: /<command>
    description: Used to leave the current dropper arena
  droppercreate:
    aliases:
      - dcreate
    permission: dropper.create
    usage: |
      /<command> <arena> <property> [new value]
      Valid properties: name, spawnLocation, exitLocation, verticalVelocity, horizontalVelocity, winBlockType
    description: Used to create a new dropper arena
  dropperedit:
    aliases:
      - dedit
    permission: dropper.edit
    usage: /<command> (Details not finalized)
    description: Used to edit an existing dropper arena
  dropperremove:
    aliases:
      - dremove
    permission: dropper.remove
    usage: /<command> <arena>
    description: Used to remove an existing dropper arena
permissions:
  dropper.*:
    description: Gives all permissions
    default: false
    children:
      - dropper.admin
  dropper.admin:
    description: Gives all permissions
    default: op
    children:
      - dropper.join
      - dropper.create
      - dropper.edit
      - dropper.remove
  dropper.join:
    description: Allows a player to participate in dropper arenas
    default: true
  dropper.create:
    description: Allows a player to create a new dropper arena
    default: false
  dropper.edit:
    description: Allows a player to edit an existing dropper arena
    default: false
  dropper.remove:
    description: Allows a player to remove a dropper arena
    default: false