name: Dropper
version: '${project.version}'
main: net.knarcraft.minigames.MiniGames
api-version: 1.19
description: A plugin that adds various mini-games
softdepend:
  - PlaceholderAPI

# Note to self: Aliases must be lowercase!
commands:
  dropperGroupSet:
    aliases:
      - dgset
    permission: dropper.edit
    usage: |
      /<command> <arena> <group>
      - The group will be created if it doesn't already exist
      - Use "none" or "null" as the group to release the arena from its group
    description: Sets the group of the given arena
  dropperGroupSwap:
    aliases:
      - dgswap
    permission: dropper.edit
    usage: |
      /<command> <arena1> <arena2>
      - The two arenas must be in the same group
    description: Swaps the order of two arenas in the same group
  dropperGroupList:
    aliases:
      - dglist
    permission: dropper.edit
    usage: |
      /<command> [group]
      - Existing groups will be listed if used without an argument
      - Supplying a group shows the group's arenas
    description: Lists existing groups and their arenas
  miniGamesReload:
    aliases:
      - mreload
    permission: dropper.admin
    usage: /<command>
    description: Reloads all data from disk
  dropperList:
    aliases:
      - dlist
    permission: dropper.join
    usage: /<command>
    description: Used to list all current dropper arenas
  dropperJoin:
    aliases:
      - djoin
    permission: dropper.join
    usage: |
      /<command> <arena> [mode]
      - Mode can be used to select challenge modes which can be played after beating the arena.
      - inverted = A game-mode where the WASD buttons are inverted
      - random = A game-mode where the WASD buttons toggle between being inverted and not
    description: Used to join a dropper arena
  miniGamesLeave:
    aliases:
      - mleave
    permission: dropper.join
    usage: /<command>
    description: Used to leave the current dropper arena
  dropperCreate:
    aliases:
      - dcreate
    permission: dropper.create
    usage: |
      /<command> <arena> <property> [new value]
      - Valid properties: name, spawnLocation, exitLocation, verticalVelocity, horizontalVelocity, winBlockType
    description: Used to create a new dropper arena
  dropperEdit:
    aliases:
      - dedit
    permission: dropper.edit
    usage: /<command> (Details not finalized)
    description: Used to edit an existing dropper arena
  dropperRemove:
    aliases:
      - dremove
    permission: dropper.remove
    usage: /<command> <arena>
    description: Used to remove an existing dropper arena
permissions:
  minigames.*:
    description: Gives all permissions
    default: false
    children:
      - minigames.admin
  minigames.admin:
    description: Gives all permissions
    default: op
    children:
      - minigames.join
      - minigames.create
      - minigames.edit
      - minigames.remove
  minigames.join:
    description: Allows a player to participate in mini-games arenas
    default: true
  minigames.create:
    description: Allows a player to create a new mini-games arena
    default: false
  minigames.edit:
    description: Allows a player to edit an existing mini-games arena
    default: false
  minigames.remove:
    description: Allows a player to remove a mini-games arena
    default: false